Kursa4/Models/SearchResult.cs
namespace Kursa4.Models;

public class SearchResult
{
    public List<Userio>? Users { get; set; }
    public List<Author>? Authors { get; set; }
    public List<Book>? Books { get; set; }
}

Kursa4/Models/ViewModel/Search.cs
namespace Kursa4.Models.ViewModel;

public class Search
{
    public string search { get; set; }
}

Kursa4/Controllers/SearchController.cs
using System.Numerics;
using AutoMapper;
using Lib.Data.Repositories;
using Kursa4.Models;
using Kursa4.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Kursa4.Controllers;
[Route("search")]
public class SearchController : Controller
{
    private readonly UowRepository _uowRepository;
    [HttpPost]
    public async Task<ActionResult> Search(Search q)
    {
        string search = q.search;
        SearchResult searchResult = new SearchResult();
        searchResult.Authors = (await _uowRepository.GenericRepository<Author>().GetAsync(x
            => x.AuthorName.Contains(search))).ToList();
        searchResult.Users =
            (await _uowRepository.GenericRepository<Userio>().GetAsync(x
                => x.FirstName.Contains(search) || x.LastName.Contains(search))).ToList();
        searchResult.Books = (await _uowRepository.GenericRepository<Book>().GetAsync(x
            => x.Title.Contains(search) || x.Disributor.Contains(search))).ToList();
        return View("SearchResult", searchResult);
    }
    public SearchController(UowRepository uowRepository)
    {
        _uowRepository = uowRepository;
    }
    [HttpGet]
    [Route("form")]
    public ActionResult FormSearch()
    {
        return View("SearchForm", new Search());
    }
    
    [HttpPost]
    [Route("books")]
    public async Task<ActionResult> SearchBooks(SearchBookQuery q)
    {
       
        if (q.SortProperty.Equals("Title"))
        {
            var los = (await _uowRepository
                .GenericRepository<Book>()
                .GetAsync(x => x.Title.Contains(q.Title) ||
                               x.Disributor.Contains(q.Disributor), orderBy: x=> 
                        x.OrderBy(x => x.Title), includeProperties:"AuthorsBooks.Author"));
            if (!los.Any())
            {
                los = await _uowRepository.GenericRepository<Book>()
                    .GetAsync(x => x.Title.Contains(x.Title) ||
                                   x.Disributor.Contains(x.Disributor), orderBy: x=> 
                        x.OrderBy(x => x.Title), includeProperties:"AuthorsBooks.Author");
            }
            if (!q.IsAlph)
            {
                los = los.Reverse();
            }
            return View("FilterAndSearch", new SearchResultUni<Book,SearchBookQuery>
            {
                List = los.ToList(), SearchQuery = q
            });
        }
        var booksResult = _uowRepository
            .GenericRepository<Book>()
            .GetAsync(x => x.Title.Contains(q.Title) ||
                           x.Disributor.Contains(q.Disributor), includeProperties:"AuthorsBooks.Author");
        return View("FilterAndSearch", new SearchResultUni<Book,SearchBookQuery>
        {
            List = (await booksResult).ToList(), SearchQuery = q
        });
    }

    [HttpGet]
    [Route("book")]
    public ActionResult SearchForm()
    {
        return View("FilterAndSearch", new SearchResultUni<Book,SearchBookQuery>());
    }

    [HttpPost]
    [Route("authors")]
    public async Task<ActionResult> SearchAuthor(SearchAuthorQuery q)
    {
        var authors = (await _uowRepository.GenericRepository<Author>().GetAsync(x 
            => x.AuthorName.Contains(q.AuthorName)));
        if (!authors.Any())
        {
            authors = await _uowRepository.GenericRepository<Author>()
                .GetAsync(x => x.AuthorName.Contains(x.AuthorName));
        }
        if (!q.IsAlph)
        {
            authors = authors.Reverse();
        }
        return View("FilterAndSearchAuthor", new SearchResultUni<Author, SearchAuthorQuery>
        {
            List = authors.ToList(), SearchQuery = q
        });
    }

    [HttpGet]
    [Route("author/find")]
    public ActionResult SearchAuthorForm()
    {
        return View("FilterAndSearchAuthor", new SearchResultUni<Author, SearchAuthorQuery>());
    }

    [HttpGet]
    [Route("user/find")]
    public ActionResult SearchUserForm()
    {
        return View("FilterAndSearchUser", new SearchResultUni<Userio, SearchUserQuery>());
    }

    [HttpPost]
    [Route("users")]
    public async Task<ActionResult> SearchUser(SearchUserQuery q)
    {
        var users = (await _uowRepository.GenericRepository<Userio>().GetAsync(x 
                => x.FirstName.Contains(q.FirstName) || x.LastName.Contains(q.LastName)));
        if (!users.Any())
        {
            users = await _uowRepository.GenericRepository<Userio>().GetAsync(x
                => x.FirstName.Contains(x.FirstName));
        }
        if (q.isAlph)
        {
            users = users.Reverse();
        }
        return View("FilterAndSearchUser", new SearchResultUni<Userio, SearchUserQuery>
        {
            List = users.ToList(), SearchQuery = q
        });
    }
}

Kursa4/Views/Search/FilterAndSearch.cshtml
@model SearchResultUni<Book, SearchBookQuery>
<link rel="stylesheet" href="~/css/book-search.css"/>
<form asp-action="SearchBooks" method="post">
        <div class="left">
            <h1>Search Book</h1>
            <label>Enter Book Title</label>
            <input type="text" name="Title"/>
            <label>Enter Book Distributor</label>
            <input type="text" name="Distributor"/>
            <label class="sortion">Sort by</label>
            <select name="SortProperty">
                <option value="Title">Title</option>
            </select>
            <input type="checkbox" name="IsAlph" value="true" checked="checked" id="check"/>
            <label for="check" class="sortion">За алфавітом</label>
            <button type="submit" class="btn-custom">Search</button>
        </div>
    </form>
    <div class="right">
        @if (@Model.List != null)
        {
            <table>
                <tr>
                    <th>Title</th>
                    <th>Author(s)</th>
                    <th>Distributor / Year</th>
                    <th>About this book</th>
                    <th colspan="3">Options</th>
                </tr>
                @foreach (var book in @Model.List)
                {
                    <tr>
                        <td class="first">
                            @book.Title
                        </td>
                        <td class="first">
                            @foreach (var author in book.AuthorsBooks)
                            {
                                @author.Author.AuthorName<br/>
                            }
                        </td>
                        <td class="first">
                            @book.Disributor
                        </td>
                        <td class="first">
                            @book.Description
                        </td>
                        <td class="second">
                            <a asp-controller="Book" asp-action="DeleteBook" asp-route-id="@book.Id">Delete</a>
                        </td>
                        <td class="second">
                            <a asp-controller="Book" asp-action="GetUpdateForm" asp-route-bookID="@book.Id">Edit</a>
                        </td>
                        <td class="second">
                            <a asp-controller="Book" asp-action="Index" asp-route-bookid="@book.Id">Show</a>
                        </td>
                    </tr>
                }
            </table>
        }
    </div>

Kursa4/Views/Search/FilterAndSearchAuthor.cshtml
@model SearchResultUni<Author, SearchAuthorQuery>
<link rel="stylesheet" href="~/css/author-search.css"/>

<form asp-action="SearchAuthor" method="post" asp-controller="Search">
    <div class="left">
        <h1>Search Author</h1>
        <label for="an">Enter Author Name</label>
        <input type="text" name="AuthorName" id="an"/>
        <label class="sortion">Sort by</label>
        <select>
            <option value="AuthorName">
                Name
            </option>
        </select>
        <input type="checkbox" name="IsAlph" value="true" checked="checked" id="check"/>
        <label for="check" class="sortion">За алфавітом</label>
        <button type="submit" class="btn-custom">Search</button>
    </div>
</form>
<div class="right">
    @if (@Model.List != null)
    {
        <table>
            <tr>
                <th>
                    Author Name
                </th>
                <th>
                    Options
                </th>
            </tr>
            <tr>
                @foreach (var author in @Model?.List)
                {
                    <td class="first">
                        @author.AuthorName
                    </td>
                    <td class="second">
                        <a asp-controller="Author" asp-action="DeleteAuthor" asp-route-id="@author.AuthorId">Delete</a>
                    </td>
                    <td class="second">
                        <a asp-controller="Author" asp-action="GetUpdateForm" asp-route-authorId="@author.AuthorId">Edit</a>
                    </td>
                    <td class="second">
                        <a asp-controller="Author" asp-action="Index" asp-route-authorid="@author.AuthorId">Show</a>
                    </td>
                    <td class="second">
                        <a asp-controller="Author" asp-action="GetAddBookForm" asp-route-authorId="@author.AuthorId">Add book</a>
                    </td>
                }
            </tr>
        </table>
    }
</div>

Kursa4/Views/Search/FilterAndSearchUser.cshtml
@model SearchResultUni<Userio, SearchUserQuery>
<link rel="stylesheet" href="~/css/user-search.css"/>

<form asp-action="SearchUser" method="post" asp-controller="Search">
    <div class="left">
        <h1>Search User</h1>
        <label for="fn">Enter First Name</label>
        <input type="text" name="FirstName" id="fn" class="input" size="30"/>
        <label for="ln">Enter Last Name</label>
        <input type="text" name="LastName" id="ln" class="input"/>
        <label class="sortion">Sort by</label>
        <select>
            <option value="FirstName">
                Name
            </option>
        </select>
        <input type="checkbox" name="IsAlph" value="true" checked="checked" id="check"/>
        <label for="check" class="sortion">За алфавітом</label>
        <button type="submit" class="btn-custom">Search</button>
    </div>
</form>
<div class="right">
    @if (@Model.List != null)
    {
        <table>
            <tr>
                <th>
                    First name
                </th>
                <th>
                    Last name
                </th>
                <th colspan="4">
                    Options
                </th>
            </tr>
            <tr>
                @foreach (var user in @Model?.List)
                {
                    <td class="first">
                        @user.FirstName
                    </td>
                    <td class="first">
                        @user.LastName
                    </td>
                    <td class="second">
                        <a asp-controller="User" asp-action="DeleteUser" asp-route-id="@user.UserId">Delete</a>
                    </td>
                    <td class="second">
                        <a asp-controller="User" asp-action="GetUpdateForm" asp-route-userId="@user.UserId">Edit</a>
                    </td>
                    <td class="second">
                        <a asp-controller="User" asp-action="Index" asp-route-userId="@user.UserId">Show</a>
                    </td>
                    <td class="second">
                        <a asp-controller="User" asp-action="GetAddBookForm" asp-route-userId="@user.UserId">Add book</a>
                    </td>
                }
            </tr>
        </table>
    }
</div>

Kursa4/Views/Search/SearchForm.cshtml
@model Search
<form asp-action="Search" method="post">
<label>Enter</label>
<input asp-for="search" class="form-control" type="text" />
<button type="submit">Submit</button>
</form>

Kursa4/Views/Search/SearchResult.cshtml
@model SearchResult

<div>
    <div>
        @if (@Model.Users != null)
        {
            @foreach (var user in @Model.Users)
            {
                @user.FirstName
                @user.LastName
            }
        }
    </div>
    <div>
        @if (@Model.Authors != null)
        {
            @foreach (var author in @Model.Authors)
            {
                @author.AuthorName
            }
        }
    </div>
    <div>
        @if (@Model.Books != null)
        {
            @foreach (var book in @Model.Books)
            {
                @book.Title
                @book.Disributor
            }
        }
    </div>
</div>